export const LOAD_COMICS = 'LOAD_COMICS';
/* LIST */
export const LOAD_COMICS_REQUESTING = 'LOAD_COMICS_REQUESTING';
export const LOAD_COMICS_SUCCESS = 'LOAD_COMICS_SUCCESS';

/* Detail */
export const LOAD_COMIC_REQUESTING = 'LOAD_COMIC_REQUESTING';
export const LOAD_COMIC_SUCCESS = 'LOAD_COMIC_SUCCESS';
