
/* LIST */
export const LOAD_CHARACTERS_REQUESTING = 'LOAD_CHARACTERS_REQUESTING';
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';

/* Detail */
export const LOAD_CHARACTER_REQUESTING = 'LOAD_CHARACTER_REQUESTING';
export const LOAD_CHARACTER_SUCCESS = 'LOAD_CHARACTER_SUCCESS';
